# Generated by Django 5.0 on 2024-01-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=240)),
                ('job_description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.CharField(max_length=240)),
                ('state', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
